# Generated by Django 5.1 on 2024-11-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id_Producto', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Precio', models.CharField(max_length=100)),
                ('Marca', models.CharField(max_length=100)),
                ('Calidad', models.CharField(max_length=100)),
                ('Recibido', models.CharField(max_length=100)),
                ('Proovedor', models.CharField(max_length=100)),
                ('Cantidad', models.CharField(max_length=100)),
            ],
        ),
    ]
